### ISSUE TITLE
no-undef-class in SASS with @import

### ISSUE THREAD

**Issue by inferusvv** [atfzl/eslint-plugin-css-modules#26]
I am trying to use Bootstrap 4 in my project. I've loaded it in my main component and all works.

Usage example: `className={s.container}`

But `no-undef-class` rule throws an error, because my bootstrap sass is just a list of imports and looks like this:

```
@import "../../node_modules/bootstrap/scss/functions";
@import "../../node_modules/bootstrap/scss/variables";
@import "../../node_modules/bootstrap/scss/mixins";
// ...
```

**Comment by atfzl** [comment]
Hi @inferusvv 
You have to use this comment to mark the bootstrap classes as used:
```js
/* eslint css-modules/no-unused-class: [2, { markAsUsed: ['container'] }] */
```

OR

you can try `composes` https://github.com/css-modules/css-modules#dependencies

**Comment by inferusvv** [comment]
@atfzl But imagine how many classes in bootstrap? All of them should be listed? It's impossible

**Comment by atfzl** [comment]
I know but it is the way css modules was made. Composing classes instead of having global classes.

**Comment by kangax** [comment]
Was there ever a feature request to support `@import`'s? @atfzl would you be open to it if I make a PR?

**Comment by atfzl** [comment]
@kangax I am open for this feature PR.

**Comment by kangax** [comment]
@atfzl cool, added in https://github.com/atfzl/eslint-plugin-css-modules/pull/42
