### ISSUE TITLE
Unused classes Found: Bracket notation

### ISSUE THREAD

**Issue by dominictwlee** [atfzl/eslint-plugin-css-modules#37]
So I passed down class names as string props to be used in a reusable component. The styles are applied correctly in the bracket notation but the linter registers them as unused classes (even though they're being used)

![props](https://user-images.githubusercontent.com/34794189/40303610-526944f0-5ceb-11e8-933b-c3f5fa8dce35.png)
![bracket-notation](https://user-images.githubusercontent.com/34794189/40303611-527e8996-5ceb-11e8-88cc-88f093c25dfe.png)
![unused-classes](https://user-images.githubusercontent.com/34794189/40303612-5294ed30-5ceb-11e8-9e62-3476a3beed7f.png)

Is this intended or a bug?

**Comment by atfzl** [comment]
@dominictwlee we are only doing static analysis on your source, we don't know what will the value of `todoList` variable at runtime.
But if you pass `<div className={styles['todoList']}>` then this will be checked.
