### ISSUE TITLE
Class names can be hyphenated

### ISSUE THREAD

**Issue by guywald1** [atfzl/eslint-plugin-css-modules#6]
styles.css:

```css
.my-class {
/* ... */
}
```

app.jsx:

```jsx
// ...
import styles from './styles.css';

const App = () => <div className={styles.myClass} />
```

creates a linting error as following:

> `css-modules/no-undef-class` Class 'myClass not found

Isn't this undesired behavior? The class can be referenced using camelCase if one feels like hyphenating their classes.

P.S. Great plugin! Thank you :)

**Comment by atfzl** [comment]
Try this:

```js
import styles from './styles.css';

const App = () => <div className={styles['my-class']} />
```

**Comment by atfzl** [comment]
I don't think hyphenated class names are converted to camelCase automatically. Can you provide a reference ?

**Comment by guywald1** [comment]
Thank you, I am actually aware of that, but that is a workaround, isn't it? The original plugin provides you with a camel-cased property for convenience.

**Comment by guywald1** [comment]
From [the plugin](https://github.com/css-modules/css-modules):

> For local class names camelCase naming is recommended, but not enforced.

**Comment by atfzl** [comment]
Can you share the value of `styles`.

```js
import styles from './styles.scss'

console.log(styles);
```

**Comment by guywald1** [comment]
```json
{
"my-style": "/* style hash is here */",
"myStyle": "/* same style has is here */"
}

**Comment by atfzl** [comment]
Hmmm, i also tried it on my setup and didn't get the camelCased version.
I am using [React Starter Kit](https://github.com/kriasoft/react-starter-kit)

I think there is a setting in the css-loader for this.

This was my loader config:
```js
{
  test: /\.scss$/,
  loaders: [
    'isomorphic-style-loader',
    `css-loader?${JSON.stringify({
            sourceMap: DEBUG,
            // CSS Modules https://github.com/css-modules/css-modules
            modules: true,
            localIdentName: DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]',
            minimize: !DEBUG
          })}`,
    'postcss-loader?pack=sass',
    'sass-loader',
  ],
},
```

**Comment by guywald1** [comment]
You need to set `camelCase: true` for `css-loader` and you'll see it.

**Comment by atfzl** [comment]
Hmm, so it is not set by default.
I can add an option for this plugin to take camelCase names, but it will take some time.

**Comment by 0xR** [comment]
This is stopping me from using eslint-plugin-css-modules

**Comment by ImanMh** [comment]
@atfzl Thanks dude, Would you give us an update? I faced the same issue today. I'm tiered of using dashes in my jsx cause it's really ugly. If you need some help give please let me know. 
Thanks.

**Comment by ImanMh** [comment]
This might help: 
```
const dashToCamel = (str) => (
  str.replace(/-.{1}/g, (g) => ( g[0] + g[1].toUpperCase())).replace(/-/g, '')
);
```
